services:
  odm:
    image: docker-eu.artifactory.swg-devops.com/hyc-odm-docker/odm:9.0.0-SNAPSHOT_24.1.0-arm64
    mem_limit: 4G
    memswap_limit: 4G
    user: "1001:0"
    environment:
    - SAMPLE=true
    - LICENSE=accept
    ports:
    - 9060:9060
    - 9453:9453
    volumes:
    - $PWD/businessvalueeditor-source/target/businessvalueeditor-1.0.jar:/config/download/businessvalueeditor-1.0.jar
    - $PWD/businessvalueeditor-source/web.xml:/config/download/web.xml
