-- Licensed Materials - Property of IBM
-- 5725-B69 5655-Y17 5655-Y31 5724-X98 5724-Y15 5655-V82
-- Copyright IBM Corp. 1987, 2022. All Rights Reserved.
--
-- Note to U.S. Government Users Restricted Rights: 
-- Use, duplication or disclosure restricted by GSA ADP Schedule 
-- Contract with IBM Corp.

DROP TABLE BOMDOMAINSAMPLE.CURRENCY;
DROP TABLE BOMDOMAINSAMPLE.STATUS;
DROP TABLE BOMDOMAINSAMPLE.MESSAGES;

DROP TABLE BOMDOMAINSAMPLE.SECTOR;
DROP TABLE BOMDOMAINSAMPLE.STOCK;

--Create Currency Table
CREATE TABLE BOMDOMAINSAMPLE.CURRENCY(ITEM_NAME VARCHAR(255) NOT NULL, ITEM_VERBALISATION VARCHAR(255) NOT NULL, ITEM_TRANSLATION VARCHAR(255) NOT NULL);

--Create Status Table
CREATE TABLE BOMDOMAINSAMPLE.STATUS(NAME VARCHAR(255) NOT NULL, DESCRIPTION VARCHAR(255) NOT NULL, CODE VARCHAR(255) NOT NULL);

--Create Messages Table
CREATE TABLE BOMDOMAINSAMPLE.MESSAGES(NAME VARCHAR(255) NOT NULL, DESCRIPTION VARCHAR(255) NOT NULL, CODE VARCHAR(255) NOT NULL);

--Create Stock Sector Table
CREATE TABLE BOMDOMAINSAMPLE.SECTOR(NAME VARCHAR(255) NOT NULL, ID INTEGER);

--Create Stock Info Table
CREATE TABLE BOMDOMAINSAMPLE.STOCK(SECTOR_ID INTEGER, STOCK_ID VARCHAR(255) NOT NULL, STOCK_NAME VARCHAR(255) NOT NULL);


-- For the value infor provider
INSERT INTO BOMDOMAINSAMPLE.SECTOR VALUES ('Telecom',1);
INSERT INTO BOMDOMAINSAMPLE.SECTOR VALUES ('Finance',2);
INSERT INTO BOMDOMAINSAMPLE.SECTOR VALUES ('Insurance',3);
INSERT INTO BOMDOMAINSAMPLE.SECTOR VALUES ('IT',4);


INSERT INTO BOMDOMAINSAMPLE.STOCK VALUES (4,'ILOG.PA','ILOG');
INSERT INTO BOMDOMAINSAMPLE.STOCK VALUES (3,'AGF.PA','AGF');
INSERT INTO BOMDOMAINSAMPLE.STOCK VALUES (2,'BNP.PA','BNP Paribas');
INSERT INTO BOMDOMAINSAMPLE.STOCK VALUES (1,'FTE.PA','France Telecom');


-- Status types
INSERT INTO BOMDOMAINSAMPLE.STATUS VALUES ('ACCEPTED','Accepted', 'return "Accepted";');
INSERT INTO BOMDOMAINSAMPLE.STATUS VALUES ('REJECTED','Rejected', 'return "Rejected";');
INSERT INTO BOMDOMAINSAMPLE.STATUS VALUES ('PENDING','Pending', 'return "Pending";');


--INSERT INTO BOMDOMAINSAMPLE.ACTION VALUES ('BUY','Buy', '"Buy"');
--INSERT INTO BOMDOMAINSAMPLE.ACTION VALUES ('SELL','Sell', '"Sell"');

-- Currency types
INSERT INTO BOMDOMAINSAMPLE.CURRENCY VALUES ('USDOLLAR','US Dollar', 'return "USD";');
INSERT INTO BOMDOMAINSAMPLE.CURRENCY VALUES ('EURO','Euro', 'return "EUR";');
INSERT INTO BOMDOMAINSAMPLE.CURRENCY VALUES ('AUSDOLLAR','Australian Dollar', 'return "AUS Dollar";');

-- Messages types
INSERT INTO BOMDOMAINSAMPLE.MESSAGES VALUES ('BlackListedStocks','Black Listed Stocks', 'return "Stock order is Black Listed";');
INSERT INTO BOMDOMAINSAMPLE.MESSAGES VALUES ('INAPPROPRIATE_CUSTOMER','Inappropriate Customer', 'return "Client situation is inappropriate, sorry";');

COMMIT;