services:
  odm:
    image: icr.io/cpopen/odm-k8s/odm:9.0.0
    mem_limit: 4G
    memswap_limit: 4G
    user: "1001:0"
    environment:
    - SAMPLE=true
    - LICENSE=accept
    ports:
    - 9060:9060
    - 9453:9453

  odm-with-gui-customization:
    image: icr.io/cpopen/odm-k8s/odm:9.0.0
    mem_limit: 4G
    memswap_limit: 4G
    user: "1001:0"
    environment:
    - SAMPLE=true
    - LICENSE=accept
    ports:
    - 9060:9060
    - 9453:9453
    volumes:
    - $PWD/target/guicustomization-1.0.jar:/config/download/guicustomization-1.0.jar 
