customization:
  runAsUser: '' # Specific to OCP
  authSecretRef: my-custom-auth-secret
image:
  pullSecrets:
    - my-odm-docker-registry
  repository: cp.icr.io/cp/cp4a/odm
decisionCenter:
  downloadUrl:
    - <FILESERVER_URL>/guicustomization-1.0.jar
internalDatabase:
  persistence:
    enabled: false
    useDynamicProvisioning: false
  runAsUser: '' # Specific to OCP
service:
  enableRoute: true # Specific to OCP
license: true
usersPassword: odmAdmin
