services:
  odm:
    image: icr.io/cpopen/odm-k8s/odm:9.0.0
    mem_limit: 4G
    memswap_limit: 4G
    user: "1001:0"
    environment:
    - SAMPLE=true
    - LICENSE=accept
    ports:
    - 9060:9060
    - 9453:9453
    volumes:
    - $PWD/group-security-configurations.xml:/config/apps/decisioncenter.war/WEB-INF/classes/config/group-security-configurations.xml
